sudo: required
dist: trusty
language: generic
notifications:
  email:
    recipients:
    - rohan@aleopile.com
    on_success: change
    on_failure: always
  slack:
    secure: QFvV//me3w8XkgmzaxPoVoqQNVLZ4055ptdEDccQHJtEZZQ5FylI+khsl8DPH4UuqkDm8VyL1rRaNK5o1e1BwZkbZFTd5gJk5mFfjAT9lR3zBlSS1VHTwoAlf3wi7KEjv3sql+ATivv36lsww4n+ESPF7Vs09wcBbOzgMNhMCNI=
before_install:
- export ROS_DISTRO=indigo
- export CI_SOURCE_PATH=$(pwd)
- export REPOSITORY_NAME=${PWD##*/}
- echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"
- sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
- sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-key 0xB01FA116
- sudo apt-get update -qq
- sudo apt-get install -qq -y ros-$ROS_DISTRO-ros-base ros-$ROS_DISTRO-catkin python-rosdep python-wstool
- sudo apt-get install -y python-catkin-pkg
- sudo rosdep init
- rosdep update
install:
- source /opt/ros/$ROS_DISTRO/setup.bash
- mkdir -p ~/ros/catkin_ws/src
- cd ~/ros/catkin_ws/src
- catkin_init_workspace
- git clone -b $TRAVIS_BRANCH https://github.com/UbiquityRobotics/ubiquity_motor.git
- rm -rf $REPOSITORY_NAME
- ln -s $CI_SOURCE_PATH .
- cd ../
- rosdep install --from-paths src --ignore-src --rosdistro $ROS_DISTRO -y
before_script:
- source /opt/ros/$ROS_DISTRO/setup.bash
script:
- catkin_make
- catkin_make run_tests
- catkin_test_results
