name: ROS Kinetic

on:
  push:
    branches: [ kinetic-devel ]
  pull_request:
    branches: [ kinetic-devel ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: ros-tooling/setup-ros@v0.1
      with:
        required-ros-distributions: melodic
      
    - uses: ros-tooling/action-ros-ci@v0.2
      with:
       package-name: ubiquity_motor
       target-ros1-distro: melodic
